### PR TITLE
Fix JSON configuration RPC public address

### PR DESCRIPTION
**Pull request by jumaffre**
Spotted by @letmaik 

These weren't in sync with the C++ code.

### CODE REVIEW

**Review by eddyashton — APPROVED** [review]

**Comment by eddyashton** [comment]
Can we add a test that runs `cchost --check` with our sample configs, to make sure they remain schema compliant?

**Comment by jumaffre** [comment]
> Can we add a test that runs `cchost --check` with our sample configs, to make sure they remain schema compliant?

There's one already: https://github.com/microsoft/CCF/blob/main/tests/e2e_operations.py#L119

**Comment by eddyashton** [comment]
> > Can we add a test that runs `cchost --check` with our sample configs, to make sure they remain schema compliant?
> 
> There's one already: https://github.com/microsoft/CCF/blob/main/tests/e2e_operations.py#L119
> 
> In this case, the validation still worked because we don't set the `additionalProperties: false` field to the objects. I've tried to set it but it doesn't have any effect, which is intriguing. I'm investigating this now but I think we can merge this PR in the meantime.

Ah, no, I think the reason this still passed is that the schema was _also_ still using the old field name. Can we add a stage to `--check`, where after running valijson to make sure it matches the schema, we try to parse it as our expected C++ type, to make sure that schema matches the code?

**Comment by jumaffre** [comment]
> > > Can we add a test that runs `cchost --check` with our sample configs, to make sure they remain schema compliant?
> > 
> > 
> > There's one already: https://github.com/microsoft/CCF/blob/main/tests/e2e_operations.py#L119
> > In this case, the validation still worked because we don't set the `additionalProperties: false` field to the objects. I've tried to set it but it doesn't have any effect, which is intriguing. I'm investigating this now but I think we can merge this PR in the meantime.
> 
> Ah, no, I think the reason this still passed is that the schema was _also_ still using the old field name. Can we add a stage to `--check`, where after running valijson to make sure it matches the schema, we try to parse it as our expected C++ type, to make sure that schema matches the code?

We do this too on `--check` (before the schema validation even): https://github.com/microsoft/CCF/blob/09ffcdf066c7eb0e20a573da799794798fe5bbd2/src/host/main.cpp#L130-L152

In this case, the schema validation was successful too because `published_address` is marked as optional in the `nlohmann::json` schema.

**Comment by eddyashton** [comment]
> 
> We do this too on `--check` (before the schema validation even):
> 
> In this case, the schema validation was successful too because `published_address` is marked as optional in the `nlohmann::json` schema.

Ahhh, my bad. Cool! Ship it!

**Pull request merged**
