### PR TITLE
Add secp256k1 to the JS crypto API

### PR DESCRIPTION
**Pull request by takuro-sato**
Issue: #4319

## Change
- Allow to pass 'secp256k1' to [`generateEcdsaKeyPair()`](https://microsoft.github.io/CCF/main/js/ccf-app/functions/crypto.generateEcdsaKeyPair.html). [`verifySignature()`](https://microsoft.github.io/CCF/main/js/ccf-app/functions/crypto.verifySignature.html) should be able to verify signatures made with secp256k1.

Note: I only changed codes related to JS crypto API. So files like `src/node/acme_client.h` is not edited.

### CODE REVIEW

**Comment by achamayou** [comment]
@takuro-sato LGTM!

Can you expand the polyfill and the test for it, and add an entry to the changelog please?

**Comment by takuro-sato** [comment]
@achamayou Do you mean editing `generateEcdsaKeyPair()` in polyfill.ts so that it can handle secp256k1?

If so I think we don't have to edit anything because the same value 'secp256k1' is used both for `generateEcdsaKeyPair()`'s parameter and `crypto.generateKeyPairSync()`'s `namedCurve` option to use secp256k1.

https://github.com/microsoft/CCF/blob/5a41af831c730e0b24abe87975591ad8f2b12540/js/ccf-app/src/polyfill.ts#L194

If I miss something, please let me know.

I'll update the changelog.

**Comment by takuro-sato** [comment]
About the polyfill's implementation,
```
takurosato@takurosato:~/forks/CCF/build$ node --version
v16.17.0
takurosato@takurosato:~/forks/CCF/build$ cat curves.js 
const crypto = require('crypto');

console.log(crypto.getCurves());



takurosato@takurosato:~/forks/CCF/build$ node curves.js | grep secp256k1
  'secp256k1',
takurosato@takurosato:~/forks/CCF/build$ node curves.js | grep secp256r1
takurosato@takurosato:~/forks/CCF/build$ 
``` 
secp256k1 is 'secp256k1' in node.js while secp256r1 is 'prime256v1'.
This is why only secp256r1 needs the following name conversion
```typescript
generateEcdsaKeyPair(curve: string): CryptoKeyPair {
    var curve_name = curve;
    if (curve == "secp256r1") curve_name = "prime256v1";
    const ecdsaKeyPair = crypto.generateKeyPairSync("ec", {
      namedCurve: curve_name,
      publicKeyEncoding: {
        type: "spki",
        format: "pem",
      },
      privateKeyEncoding: {
        type: "pkcs8",
        format: "pem",
      },
    });
    return ecdsaKeyPair;
  }
```

Again, please let me know if I missed anything.

**Review by achamayou — APPROVED** [review]
Thank you @takuro-sato!

**Pull request merged**
