### PR TITLE
Are JVM defaults good enough for our purposes?

### PR DESCRIPTION
**Pull request by achamayou**
We seem to be using a lot of flags to tell the JVM about memory, and I am not convinced they are needed for our usage at this moment in time.

### CODE REVIEW

**Comment by heidihoward** [comment]
These options are also set in https://github.com/microsoft/CCF/blob/main/.github/workflows/tlaplus.yml and https://github.com/microsoft/CCF/blob/main/tla/install_deps.py

**Comment by achamayou** [comment]
> These options are also set in https://github.com/microsoft/CCF/blob/main/.github/workflows/tlaplus.yml and https://github.com/microsoft/CCF/blob/main/tla/install_deps.py

So they are, thank you!

**Review by eddyashton — APPROVED** [review]

**Comment by lemmy** [comment]
A few years ago, I ran performance measurements with `-XX:+UseParallelGC` and saw a noticeable performance benefit compared to the default, latency-optimized GC. Is it possible that newer JVM versions have eliminated this performance gap?

**Comment by achamayou** [comment]
> Is it possible that newer JVM versions have eliminated this performance gap?

I've tried looking through JRE releases notes, and they were surprisingly painful to gather. There's been a lot of changes, but at least the defaults for Xms and Xmx have been revised several times, and are platform dependent too.

Simulation time appears unchanged:

Before: https://github.com/microsoft/CCF/actions/runs/6272070572 - 10 min 35 s
After: https://github.com/microsoft/CCF/actions/runs/6356023869 - 10 min 28 s

Same with trace validation:

Before: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=76603&view=logs&j=0c81e209-1101-513f-1f15-37e9c3575eb2 - 19 s
After: https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=76681&view=logs&j=0c81e209-1101-513f-1f15-37e9c3575eb2&t=a05664f3-ab91-5eb2-6acd-14e2179ad708 - 18 s

Model checking does seem to have gone up:

Before: https://github.com/microsoft/CCF/actions/runs/6273245621 - 22 min 13 s
After: https://github.com/microsoft/CCF/actions/runs/6356023869 - 31 min 49 s

I'll do a few more runs to see if this is conclusively related (we use a default public pool for that job, performance isn't particularly consistent), but there isn't a good reason for these flags at least for simulation and tracing.

**Comment by achamayou** [comment]
Looking at the cost of a few options:

`-coverage`

**With:** `time java -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=be29f6283abeed2fb1fd0be898bc6601 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -checkpoint 60 -coverage 60 -tool MCccfraft.tla 2>&1`

```
real    1m46.869s
user    13m53.430s
sys     0m1.609s
```

**Without:** `time java -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=be29f6283abeed2fb1fd0be898bc6601 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -checkpoint 60 -tool MCccfraft.tla 2>&1`

```
real    1m1.045s
user    7m51.213s
sys     0m1.875s
```

`-checkpoints`

**Without:**

```
real    1m0.140s
user    7m43.943s
sys     0m1.923s
```

Little difference there, but probably still not very useful in CI unless we archive them.

**Comment by heidihoward** [comment]
> Simulation time appears unchanged:
> 
> Before: https://github.com/microsoft/CCF/actions/runs/6272070572 - 10 min 35 s After: https://github.com/microsoft/CCF/actions/runs/6356023869 - 10 min 28 s
> 

The simulation has a time budget of 10 mins, so I would not expect to see a change there

**Comment by heidihoward** [comment]
> `-checkpoints`
> 
> **Without:**
> 
> ```
> real    1m0.140s
> user    7m43.943s
> sys     0m1.923s
> ```
> 
> Little difference there, but probably still not very useful in CI unless we archive them.

 `-checkpoint 60` means checkpoint once every 60 mins so I wouldn't expect it to make much difference when a model runs for 8 mins 
https://github.com/tlaplus/tlaplus/blob/master/general/docs/current-tools.md#command-line-options

**Comment by heidihoward** [comment]
> `-checkpoints`
> 
> **Without:**
> 
> ```
> real    1m0.140s
> user    7m43.943s
> sys     0m1.923s
> ```

By the way, I believe that removing `checkpoint 60` means that checkpointing reverts to the default of checkpointing every 30 mins instead of disabling checkpointing. I don't think there's any way to fully disable checkpointing.

**Comment by heidihoward** [comment]
Sorry for the long stream of replies

> Looking at the cost of a few options:
> 
> `-coverage`
> 
> **With:** `time java -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=be29f6283abeed2fb1fd0be898bc6601 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -checkpoint 60 -coverage 60 -tool MCccfraft.tla 2>&1`
> 
> ```
> real    1m46.869s
> user    13m53.430s
> sys     0m1.609s
> ```
> 
> **Without:** `time java -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=be29f6283abeed2fb1fd0be898bc6601 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -checkpoint 60 -tool MCccfraft.tla 2>&1`
> 

This roughly matches my experience. I ran a few tests locally and the difference between no coverage and `coverage 60` is roughly a factor of two. `coverage 60` is still fairly useful (at least during the development of specs) as the coverage info is available at the end of checking (even if checking took less than 60 mins) and I often manually check for actions that have 0 coverage unexpectedly. See screenshot below.

image

**Comment by achamayou** [comment]
@heidihoward it sounds to me like `-coverage` can be set in manual runs then, for example through `_JAVA_OPTIONS`, but I don't think we should have it in the CI.

**Comment by achamayou** [comment]
> > Simulation time appears unchanged:
> > Before: https://github.com/microsoft/CCF/actions/runs/6272070572 - 10 min 35 s After: https://github.com/microsoft/CCF/actions/runs/6356023869 - 10 min 28 s
> 
> The simulation has a time budget of 10 mins, so I would not expect to see much change there

Doh, of course. So we do seem to be generating somewhat fewer states (~9%) post-change, 678329 vs 744363.

**Comment by achamayou** [comment]
@lemmy reverting to the default GC makes the runtime grow by about 15% for model checking, so I'll put that back.

```
time java -XX:+UseParallelGC -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=be29f6283abeed2fb1fd0be898bc6601 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -tool MCccfraft.tla 2>&1

real    0m59.279s
user    7m36.310s
sys     0m2.693s

real    0m56.746s
user    7m16.754s
sys     0m2.681s

real    0m59.181s
user    7m36.114s
sys     0m2.561s

time java -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=be29f6283abeed2fb1fd0be898bc6601 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -tool MCccfraft.tla 2>&1

real    1m2.915s
user    8m0.579s
sys     0m2.198s

real    1m1.451s
user    7m47.127s
sys     0m2.190s

real    1m2.192s
user    7m58.164s
sys     0m2.128s
```

**Comment by lemmy** [comment]
> @lemmy reverting to the default GC makes the runtime grow by about 15% for model checking, so I'll put that back.
> 
> ```
> time java -XX:+UseParallelGC -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=be29f6283abeed2fb1fd0be898bc6601 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -tool MCccfraft.tla 2>&1
> 
> real    0m59.279s
> user    7m36.310s
> sys     0m2.693s
> 
> real    0m56.746s
> user    7m16.754s
> sys     0m2.681s
> 
> real    0m59.181s
> user    7m36.114s
> sys     0m2.561s
> 
> time java -Dtlc2.TLC.ide=Github -Dutil.ExecutionStatisticsCollector.id=be29f6283abeed2fb1fd0be898bc6601 -cp tla2tools.jar tlc2.TLC -workers auto -lncheck final -tool MCccfraft.tla 2>&1
> 
> real    1m2.915s
> user    8m0.579s
> sys     0m2.198s
> 
> real    1m1.451s
> user    7m47.127s
> sys     0m2.190s
> 
> real    1m2.192s
> user    7m58.164s
> sys     0m2.128s
> ```

Thanks for confirming. :-)

**Comment by achamayou** [comment]
> Thanks for confirming. :-)

Sorry, that was a little trigger happy, but the proliferation of flags was making me a little nervous. I'm glad it was possible consolidate in #5702.

**Pull request merged**
