### PR TITLE
Switch to Open Enclave 0.17.0 rc1

### PR DESCRIPTION
**Pull request by achamayou**
Testing 0.17 rc1, without upgrading clang or Ubuntu for now.

As usual, the perf env will require a separate change.

### CODE REVIEW

**Comment by achamayou** [comment]
jwt_test fails

```
53: 10:47:15.828 | INFO     | infra.remote:log_errors:77 - 2021-06-21T10:47:15+0000.345904Z [(H)ERROR] tid(0x7fbd43a8c700) | Invalid platform TCB level: OutOfDate (cpu_svn[0] = 0xf, pce_svn = 0xa) [/source/openenclave/common/sgx/tcbinfo.c:oe_parse_tcb_info_json:825]
53: 10:47:15.828 | INFO     | infra.remote:log_errors:77 - 2021-06-21T10:47:15+0000.347483Z [(H)ERROR] tid(0x7fbd43a8c700) | :OE_TCB_LEVEL_INVALID [/source/openenclave/common/attest_plugin.c:oe_verify_attestation_certificate_with_evidence_v2:590]
53: 10:47:15.828 | INFO     | infra.remote:log_errors:77 - 2021-06-21T10:47:15+0000.347502Z [(H)ERROR] tid(0x7fbd43a8c700) | oe_verify_attestation_certificate_with_evidence() failed with error = OE_TCB_LEVEL_INVALID
```

**Comment by achamayou** [comment]
`/opt/openenclave/bin/oeutil generate-evidence -f cert` allows us to generate certs with fresh attestations in them, we should switch the jwt_test to do that.

**Review by eddyashton — APPROVED** [review]

**Comment by achamayou** [comment]
Calls to oeutil inside docker do not seem to work, for reasons unclear so far:

```
53: 17:36:05.172 | DEBUG    | infra.proc:ccall:15 - stdout: NOTICE: oeutil generate-evidence is purely a debugging utility and not suitable for production use.
53: 
53: 2021-06-23T17:36:05+0000.171228Z [(H)ERROR] tid(0x7f7fc9cb9c00) | enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR) [/source/openenclave/host/sgx/sgxload.c:oe_sgx_create_enclave:402]
```

**Comment by achamayou** [comment]
Updating perf env now, since other jobs are now passing.

**Pull request merged**
