### PR TITLE
Restrict initial configuration in ccfraft.tla to a single node

### PR DESCRIPTION
**Pull request by heidihoward**
This is a simple change which probably has some big implications for the TLA+ specs and the trace validation.

### CODE REVIEW

**Comment by heidihoward** [comment]
Linking https://github.com/microsoft/CCF/pull/5769

**Comment by lemmy** [comment]
Trace validation redefines `InitReconfigurationVars` with `TraceInitReconfigurationVars`, which may initialize configuration to a *set of servers* if that's what's in the log.  For example, tests/raft_scenarios/election initializes the configuration of the first node `0` to `{0,1,2}`.

**Comment by heidihoward** [comment]
My understanding from @achamayou is that the initial configuration is always a single server. https://github.com/microsoft/CCF/pull/5769 should help this bootstrapping phase to be represented in the raft driver

**Comment by lemmy** [comment]
Should we change `TraceInitReconfigurationVars` accordingly in this PR?

**Review by achamayou — APPROVED** [review]

**Comment by heidihoward** [comment]
> Should we change `TraceInitReconfigurationVars` accordingly in this PR?

Yes. I've taken a quick look at it (alongside the traces shared by @achamayou) and I'm not sure the best direction to take

**Review by achamayou — APPROVED** [review]

**Comment by lemmy** [comment]
> > Should we change `TraceInitReconfigurationVars` accordingly in this PR?
> 
> Yes. I've taken a quick look at it (alongside the traces shared by @achamayou) and I'm not sure the best direction to take

Since Traceccfraft is in flux right now because of @achamayou's work on aligning the raft test driver, it might be a good idea to simply add a TODO in Traceccfraft to realign it with ccfraft eventually.

**Pull request merged**
