### PR TITLE
Avoid deadlock by queuing message writes on the host

### PR DESCRIPTION
**Pull request by eddyashton**
This is a proposed fix for #628.

This adds a new implementation of `ringbuffer::AbstractWriter` which avoids blocking indefinitely - if the underlying ringbuffer is full, it will add messages to an internal queue. This queue can be flushed later, periodically, when the ringbuffer should have space, to write the queued messages. This has less knock-on effects on the calling code than making them call `try_write` and handle failures individually, at each calling point. Instead each write-point can stick with their looks-like-a-blocking-call call, and the details are handled beneath their feet.

There are 2 new unit tests for this. One in `messaging.cpp` which checks this lets us write past a full ringbuffer, and one in `oversized.cpp` which checks this integrates nicely with our existing `oversized` message fragmentation writer.

These writer implementations now use composition rather than inheritance for slightly awkward reasons - I'm not sure if this is strictly necessary, but has been easier to reason about the behavioural combinations. The chain on the host side is that we talk to a fragment-if-oversized `oversized::Writer`, which actually writes by sending things to a queue-if-full `ringbuffer::NonBlockingWriter`, which tries to send to the actual memory buffer with a `ringbuffer::Writer`. In the enclave, we don't have the `NonBlocking` intermediary - the enclave's write attempts will block until the host frees outbound ringbuffer space.

We maintain ordering of messages within a single writer - if any messages _are_ pending, then future writes must be added to the queue. Only by flushing to an empty queue will we start trying to write new messages to the ringbuffer again.

I'm not very enthused with the `NonBlocking` naming, but its the best I've found so far. I was working with `PendingQueue`, which is much worse. Feel free to rename.

### CODE REVIEW

**Comment by cimetrics** [comment]
images

**Comment by achamayou** [comment]
@eddyashton OverflowWriter perhaps? This looks good to me, we seem to have some instances of the deadlock in the CI, so I think we should look at getting this in sooner rather than later. We can always revisit it as part of the performance work.

**Comment by cimetrics** [comment]
images

**Comment by cimetrics** [comment]
images

**Pull request merged**
