### PR TITLE
pass log path to remote class

### PR DESCRIPTION
**Pull request by olgavrou**

### CODE REVIEW

**Comment by cimetrics** [comment]
images

**Comment by cimetrics** [comment]
images

**Comment by achamayou** [comment]
This is fine, but just for context, why do we need this change?

**Comment by olgavrou** [comment]
I think that during the big light genesis PR, we stopped passing in the log_path to the remote class. It's needed so that if it is set, the logs will be copied to the log_path location to be collected by Azure Log Analytics

**Pull request merged**
