### PR TITLE
Split network identity from ledger secrets

### PR DESCRIPTION
**Pull request by jumaffre**
Resolves first tick box in https://github.com/microsoft/CCF/issues/50. 

So far, the network secrets (i.e. ledger secrets and network identity) were treated as one, and updated in one go during recovery. For re-keying purposes, members should be able to only update the current ledger secret. This PR is mostly refactoring to separate the two.

### CODE REVIEW

**Comment by cimetrics** [comment]
split_network_identity_from_ledger_key@[3671 aka 20200107.6](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=3671&view=results) vs master ewma over 20 builds from [3599](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=3599&view=results) to [3669](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=3669&view=results)
images

**Comment by cimetrics** [comment]
split_network_identity_from_ledger_key@[3673 aka 20200107.7](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=3673&view=results) vs master ewma over 20 builds from [3599](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=3599&view=results) to [3669](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=3669&view=results)
images

**Comment by eddyashton** [comment]
CIMetrics shows a 52% reduction in smallbank throughput - looks like a one-off? Separately: New CIMetrics rendering is great, but we should tag the metrics we'd like to increase vs decrease.

**Comment by jumaffre** [comment]
> CIMetrics shows a 52% reduction in smallbank throughput - looks like a one-off, any explanation? Separately: New CIMetrics rendering is great, but we should tag the metrics we'd like to increase vs decrease.

Good spot. Not sure what happened there, but it looks like a one-off indeed. I've triggered another build to check.

**Comment by jumaffre** [comment]
From another build of same branch, https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=3674&view=results. 
```
48: 2020-01-07 12:44:15.222 | DEBUG    | infra.remote:_print_upload_perf:101 - 	=> 42074.4tx/s
48: 2020-01-07 12:44:15.222 | SUCCESS  | infra.remote:_print_upload_perf:105 - METRICS: Small_Bank_ClientCpp_SGX_CFT_FTCP = 42074.4
```

**Pull request merged**
