### PR TITLE
Minimal repro triggering the issue in ccfraft.tla AdvanceCommitIndex

### PR DESCRIPTION
**Pull request by achamayou**
AdvanceCommitIndex always picks [the smallest possible index to move commit to](https://github.com/microsoft/CCF/blob/af214078fd067f578d393665c451ae3f9af2401e/tla/consensus/ccfraft.tla#L712), which breaks on traces as soon as there is more than one signature pending.

See trace produced under https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=78092&view=logs&j=0c81e209-1101-513f-1f15-37e9c3575eb2&t=a05664f3-ab91-5eb2-6acd-14e2179ad708

### CODE REVIEW

**Comment by lemmy** [comment]
Build is green because *_deprecated scenarios do not run.

**Comment by heidihoward** [comment]
The link to the trace is no longer working. Would it be possible to increase the retention time for ADO build logs?

**Comment by lemmy** [comment]
> The link to the trace is no longer working. Would it be possible to increase the retention time for ADO build logs?

If you need to recreate the trace/log, checking out the commit on a Codespace is relatively straight forward.

**Comment by heidihoward** [comment]
I had a go at reproducing this against the latest version but it wasn't successful, I assume that is due to the changes in the trace validation since. 

<details>
<summary>Output</summary>

```
JSON=../build/replicate_deprecated.ndjson ./tlc.sh consensus/Traceccfraft.tla 
TLC2 Version 2.18 of Day Month 20?? (rev: 79c86b5)
Running breadth-first search Model-Checking with fp 94 and seed 4637506532843996040 with 1 worker on 32 cores with 27305MB heap and 64MB offheap memory [pid: 2998] (Linux 6.2.0-1018-azure amd64, Ubuntu 11.0.21 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /workspaces/CCF/tla/consensus/Traceccfraft.tla
Parsing file /workspaces/CCF/tla/consensus/ccfraft.tla
Parsing file /tmp/tlc-3039395389646040712/Json.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/Json.tla)
Parsing file /tmp/tlc-3039395389646040712/IOUtils.tla (jar:file:/workspaces/CCF/tla/CommunityModules-deps.jar!/IOUtils.tla)
Parsing file /tmp/tlc-3039395389646040712/Sequences.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/Sequences.tla)
Parsing file /tmp/tlc-3039395389646040712/_TLCTrace.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/_TLCTrace.tla)
Parsing file /tmp/tlc-3039395389646040712/Naturals.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/Naturals.tla)
Parsing file /tmp/tlc-3039395389646040712/FiniteSets.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/FiniteSets.tla)
Parsing file /tmp/tlc-3039395389646040712/TLC.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/TLC.tla)
Parsing file /tmp/tlc-3039395389646040712/FiniteSetsExt.tla (jar:file:/workspaces/CCF/tla/CommunityModules-deps.jar!/FiniteSetsExt.tla)
Parsing file /tmp/tlc-3039395389646040712/SequencesExt.tla (jar:file:/workspaces/CCF/tla/CommunityModules-deps.jar!/SequencesExt.tla)
Parsing file /tmp/tlc-3039395389646040712/Functions.tla (jar:file:/workspaces/CCF/tla/CommunityModules-deps.jar!/Functions.tla)
Parsing file /workspaces/CCF/tla/consensus/Network.tla
Parsing file /tmp/tlc-3039395389646040712/Bags.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/Bags.tla)
Parsing file /tmp/tlc-3039395389646040712/Folds.tla (jar:file:/workspaces/CCF/tla/CommunityModules-deps.jar!/Folds.tla)
Parsing file /tmp/tlc-3039395389646040712/Integers.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/Integers.tla)
Parsing file /tmp/tlc-3039395389646040712/TLCExt.tla (jar:file:/workspaces/CCF/tla/tla2tools.jar!/tla2sany/StandardModules/TLCExt.tla)
Semantic processing of module Naturals
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module TLC
Semantic processing of module Folds
Semantic processing of module Functions
Semantic processing of module FiniteSetsExt
Semantic processing of module SequencesExt
Semantic processing of module Bags
Semantic processing of module Network
Semantic processing of module ccfraft
Semantic processing of module Json
Semantic processing of module Integers
Semantic processing of module IOUtils
Semantic processing of module TLCExt
Semantic processing of module _TLCTrace
Semantic processing of module Traceccfraft
Starting... (2024-01-05 10:27:03)
<<"Trace:", "../build/replicate_deprecated.ndjson", "Length:", 65>>  3
<<"Trace:", "../build/replicate_deprecated.ndjson", "Length:", 65>>  3
Implied-temporal checking--satisfiability problem has 1 branches.
Computing initial states...
Finished computing initial states: 0 distinct states generated at 2024-01-05 10:27:04.
Progress(1) at 2024-01-05 10:27:04: 0 states generated, 0 distinct states found, 0 states left on queue.
Checking temporal properties for the complete state space with 0 total distinct states at (2024-01-05 10:27:04)
Finished checking temporal properties in 00s at 2024-01-05 10:27:04
Model checking completed. No error has been found.
  Estimates of the probability that TLC did not check all reachable states
  because two distinct states had the same fingerprint:
  calculated (optimistic):  val = 0.0
0 states generated, 0 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 0.
Finished in 00s at (2024-01-05 10:27:04)
```
</details>

**Comment by achamayou** [comment]
@heidihoward it looks like that did not check anything:

```
0 states generated, 0 distinct states found, 0 states left on queue.
The depth of the complete state graph search is 0.
```

I believe this is fixed by #5879, we can hopefully make progress on the realistic scenarios again with that out of the way.

**Pull request closed without merging**
