### PR TITLE
Tlai experiment

### PR DESCRIPTION
**Pull request by achamayou**
The usual re-creation as a branch because of TLAi permissions, see #6132

### CODE REVIEW

**Comment by achamayou** [comment]
image

I give up.

**Comment by lemmy** [comment]
Apparently an intermittent issue:

image

**Comment by lemmy** [comment]
@pelikhan Is there any non-determinism in relevant parts of GenAIScript that could explain this?

**Comment by pelikhan** [comment]
This happens when we tried to read the LLM configuration information from the environment variables, like OPENAI_API_KEY, ... so there should not be anything non-deterministic.

I will add more logging in genaiscript to list the environment variables it found; but could it be that those are missing in the run? We could have a quick prescript that makes sure the OPENAI_API_KEY is set.

**Comment by lemmy** [comment]
It could have been an intermittent Github action issue, but I think it's less likely.

**Comment by pelikhan** [comment]
I will push a new cli with added logging.

**Comment by achamayou** [comment]
@lemmy yes, it's not on all the runs, and I can't see any obvious pattern to it. The PR would not have worked anyway because it looks like TLAi only looks at diffs, not whole files.

**Pull request closed without merging**
