### PR TITLE
Another attempt at ignoring RVRs and AERs when not in the right state

### PR DESCRIPTION
**Pull request by achamayou**
Alternative to #5347

### CODE REVIEW

**Comment by eddyashton** [comment]
NB: This includes the changes in #5355.

**Comment by achamayou** [comment]
> NB: This includes the changes in #5355.

Yes, this is just pipelined in case/after we merge it.

**Review by lemmy — APPROVED** [review]
LGTM

**Review by eddyashton — APPROVED** [review]

**Comment by lemmy** [comment]
@achamayou Cherry-picking e68f1cd8dcb0513ab70a55353f28e3ee8b05f98a on top of https://github.com/microsoft/CCF/pull/5351 validates all existing traces.

**Pull request merged**
