### PR TITLE
Relax retransmission criteria

### LINKED ISSUE #860: Primary not retransmitting forwarded requests
There is a corner case in PBFT where view changes will be triggered when there is no need for it. The scenario is (for a request with rid: `r`)

Notes:
- Primary (A) re-transmits requests when it receives status messages from other replicas
- A replica (B) that is a little bit behind (not a late joiner) will send out status messages

Bug explained:

- Replica (B) gets a request `r` and the related information it needs to execute and commit
- Replica (B) will execute for `r` at seqno `n`
- The primary (A) which is already further ahead will get (B)s status message and retransmit request `r`
- Replica (B) will re-receive request `r`, won't be able to add it to the "big request queue" causing it to be added to its `rqueue` which tracks requests and issues view changes if they haven't been executed
- Replica (B) forwards the request `r` to the primary and starts the view change timer
- The primary (A) will receive the request `r` but not via the client proxy, so the request `r` will not be broadcasted as is done usually to the other replicas
- The primary (A) will execute the request, send out pre-prepare with seqno `n'` to the other replicas, advance its last tentative execution seqno, and wait for prepares/commits from other replicas for seqno `n'`
- The other replicas will receive the pre-prepare, but they do not have the request `r` since it has not been broadcasted to them again, they will never be able to prepare/commit for this request
- The primary (A) can't make progress because it first needs to commit for request `r` at seqno `n'`
- No progress is being made while primary (A) is blocked so replica (B) and the others in time, will issue a view change

It is OK for now to execute requests again since we do not offer exactly once semantics and that should be left to the app, but if a request gets executed on the primary the other replicas _should_ be able to execute it too, so the request needs to be broadcasted.

### PR DESCRIPTION
**Pull request by olgavrou**
Resolves #860 

`pc.num_correct()` checks Certificate `c->count` which only increases when we add a prepare, but doesn't increase when we add a pre-prepare to a `Prepared_cert` of the `plog`.

Therefore if a backup replica had received a pre-prepare but not a prepare for a specific request and the request was missing, it would not have increased the `c->count` of the `Prepared_cert` so `pc.num_correct()` would be `0`.

This would result in the backup not asking the primary to retransmit the missing request for that received pre-prepare.

### CODE REVIEW

**Comment by cimetrics** [comment]
retransmit_req@[5150 aka 20200221.5](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=5150&view=results) vs master ewma over 30 builds from [4830](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=4830&view=results) to [5145](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=5145&view=results)
images

**Comment by ashamis** [comment]
As per the attached bug, how often does the retransmission occur?

**Comment by olgavrou** [comment]
@ashamis these retransmissions occur very rarely with `0` worker threads but every ~5 test runs when worker threads are set to `2`

**Comment by olgavrou** [comment]
This is not the correct solution for this problem, closing the PR.

**Pull request closed without merging**
