### PR TITLE
Uninstall handler

### PR DESCRIPTION
**Pull request by jumaffre**
The new `create` handle should only be available once, when starting the first node of a new network.

Since the handlers are installed in the constructor of a `frontend`, it is easier to uninstall after the fact, once we know the starting mode, than install it only when we know we're going to use it.

### CODE REVIEW

**Comment by cimetrics** [comment]
images

**Comment by olgavrou** [comment]
As discussed offline, it would be better to check `args.start_type` in `nodestate.h` first and if it isn't `StartType::New` then uninstall the handler, instead of uninstalling in each switch case. We might add another `StartType` and forget to uninstall.

**Comment by cimetrics** [comment]
images

**Comment by cimetrics** [comment]
images

**Comment by cimetrics** [comment]
images

**Comment by cimetrics** [comment]
images

**Pull request merged**
