### PR TITLE
Log values of committable_indices in TLA+ validation JSON logging

### PR DESCRIPTION
**Pull request by lemmy**
https://github.com/microsoft/CCF/issues/5057

Towards validating fancy_election.1 and suffix_collision.2.

### CODE REVIEW

**Comment by achamayou** [comment]
@lemmy because tracing is enabled in all debug builds, and committable indices gets large in some tests, this change makes them substantially slower, to the point where the CI times out.

I can think of two options, but there may be more:

1. The spec maintains a committable indices based on the committable flag emitted in the messages.
2. We split the build for trace validation, instead of reusing the debug build, to minimise the impact of this change on runtime.

**Comment by lemmy** [comment]
For now it would suffice to just log the max committable index (to compare it to `MaxCommittableIndex(log[i])` for the current node.  Would that be acceptable?

**Comment by achamayou** [comment]
@lemmy yes, that seems fine, the serialisation and I/O cost should be much less.

**Comment by lemmy** [comment]
> @lemmy yes, that seems fine, the serialisation and I/O cost should be much less.

Done

**Review by achamayou — APPROVED** [review]

**Pull request merged**
