### PR TITLE
Subset of small improvements of TLA+ specification listed in #4264

### PR DESCRIPTION
**Pull request by lemmy**
@heidihoward Removes some bottlenecks for TLC.

### CODE REVIEW

**Comment by heidihoward** [comment]
Thank you so much @lemmy for this PR. I will fix the CI and then get this merged in :)

**Comment by heidihoward** [comment]
@lemmy do we need to switch to the nightly build of `tla2tools` to utilize this? We can do if needs be, but I would slightly prefer to stay with released versions if possible.

I added community modules to my setup (using TLC2 Version 2.17, openjdk 11.0.14) and it failed with the following error. This error was fixed by switching to the nightly build of tla2tools.
```
./tlc.sh MCccfraft.tla
TLC2 Version 2.17 of 02 February 2022 (rev: 3c7caa5)
Running breadth-first search Model-Checking with fp 124 and seed -6425712241891470167 with 8 workers on 8 cores with 1963MB heap and 64MB offheap memory [pid: 1770] (Linux 5.10.102.1-microsoft-standard-WSL2 amd64, Ubuntu 11.0.14 x86_64, MSBDiskFPSet, DiskStateQueue).
Parsing file /home/heidi/CCF-lemmy/tla/MCccfraft.tla
Parsing file /home/heidi/CCF-lemmy/tla/ccfraft.tla
Parsing file /tmp/TLC.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Sequences.tla
Parsing file /tmp/FiniteSetsExt.tla
Parsing file /tmp/SequencesExt.tla
Parsing file /tmp/Functions.tla
Parsing file /tmp/Folds.tla
Semantic processing of module Naturals
Semantic processing of module Sequences
Semantic processing of module FiniteSets
Semantic processing of module TLC
Semantic processing of module Folds
Semantic processing of module Functions
Semantic processing of module FiniteSetsExt
Semantic processing of module SequencesExt
Semantic processing of module ccfraft
Semantic processing of module MCccfraft
Starting... (2022-10-18 22:50:11)
Loading SequencesExt!ReplaceFirstSubSeq operator override from jar:file:/home/heidi/CCF-lemmy/tla/CommunityModules.jar!/tlc2/overrides/SequencesExt.class with signature: <Java Method: public static tlc2.value.impl.Value tlc2.overrides.SequencesExt.replaceFirstSubSeq(tlc2.tool.impl.Tool,tla2sany.semantic.ExprOrOpArgNode[],tlc2.util.Context,tlc2.tool.TLCState,tlc2.tool.TLCState,int,tlc2.tool.coverage.CostModel)>.
Loading SequencesExt!ReplaceAllSubSeqs operator override from jar:file:/home/heidi/CCF-lemmy/tla/CommunityModules.jar!/tlc2/overrides/SequencesExt.class with signature: <Java Method: public static tlc2.value.impl.Value tlc2.overrides.SequencesExt.replaceAllSubSeq(tlc2.tool.impl.Tool,tla2sany.semantic.ExprOrOpArgNode[],tlc2.util.Context,tlc2.tool.TLCState,tlc2.tool.TLCState,int,tlc2.tool.coverage.CostModel)>.
Error: TLC threw an unexpected exception.
This was probably caused by an error in the spec or model.
See the User Output or TLC Console for clues to what happened.
The exception was a java.lang.NoClassDefFoundError
: tlc2/value/impl/KSubsetValue
Finished in 00s at (2022-10-18 22:50:11)
``

**Comment by lemmy** [comment]
If need be, relevant CommunityModule additions can likely be backported to work with the *released* version of TLC.  That said, it would likely be less work to release a new version of TLC -- the main reason why there is no recent release is a shortage in release engineering manpower, and not because TLC has seen revolutionary changes with high risks of regressions.

**Comment by heidihoward** [comment]
No worries, let's switch to the nighly build (YOLO) and we can re-evaluate after the next release

**Comment by heidihoward** [comment]
I think this PR is ready for review. 

If anyone would like to use codespaces then you can try it out by going to the branch and doing code -> configure and create codespace -> changing dev container configuration from default to `.devcontainer/tlaplus/devcontainer.json` -> create codespace.

**Comment by lemmy** [comment]
> If anyone would like to use codespaces then you can try it out by going to the branch and doing code -> configure and create codespace -> changing dev container configuration from default to `.devcontainer/tlaplus/devcontainer.json` -> create codespace.

For Microsoft employees to get (universal) access to Codespaces, follow the instructions at https://repos.opensource.microsoft.com/link

**Comment by lemmy** [comment]
FYI: There is still one addition to the CommunityModules pending that introduces `SequencesExt!IsCommonPrefixWhile` that simplifies and speeds up `LogMatchingInv`.

**Comment by heidihoward** [comment]
That sounds wonderful! I'm quite excited about getting this merged into main so I'm happy to proceed with getting this upstreamed and to create a new PR once `SequencesExt!IsCommonPrefixWhile` is avalaible.

**Comment by lemmy** [comment]
OK

**Review by achamayou — APPROVED** [review]

**Review by heidihoward — APPROVED** [review]

**Comment by heidihoward** [comment]
This PR is good to go. The CCF Github pages and CI jobs are hanging so waiting for another commit to main to force retry

**Comment by achamayou** [comment]
This is failing the Pages CI for a silly reason, filed as #4395, and will not impact the main CI since we do not (yet (*)) run TLA in CI.

(*) I have a dream.

**Pull request merged**
