### PR TITLE
Check refinement of high-level spec abs for configs with reconfiguration.

### PR DESCRIPTION
**Pull request by lemmy**
Precursor to https://github.com/microsoft/CCF/pull/6475

### CODE REVIEW

**Comment by lemmy** [comment]
`MCccfraftWithReconfig` fails with an expected:

```
Error: Evaluating action property line 51, col 20 to line 51, col 33 of module abs failed.
Attempted to construct a set with too many elements (>1000000).
```

`MCccfraftAtomicReconfig` fails with unexpected that warrants further investigation:

```
Error: Action property line 51, col 20 to line 51, col 33 of module abs is violated.
Error: The behavior up to this point is:
```

**Comment by achamayou** [comment]
@lemmy I am not sure I understand why the first one is expected, at first I thought the cLogs were getting big, but surely they're no bigger than the full logs we keep in ccfraft?

I had a look at the second one, I had to hack up the sim viz a bit to cope with name changes and retirement, and got this:

image

That looks fine to me. At first I thought it failed because it bumped against MCMaxLogLength == 7, but we're a lot more generous in MCccfraftAtomicReconfig.cfg, so I don't think it's that.

**Comment by lemmy** [comment]
`MCccfraftAtomicReconfig`: The transition (`AdvanceCommitIndex(n2)`) from [state 44 to state 45](https://github.com/microsoft/CCF/actions/runs/10976910483/job/30479045843) (some variables elided) is not an `abs!Copy` or `abs!Extend` action. In other words, the next-state relation of abs equals false for this transition.  The refinement mapping only relates the *committed* logs of the servers.  
* `abs!Copy`: `n2` doesn't append a suffix from `n1`'s log. Instead, it appends a suffix that seems unrelated, emerging unexpectedly based on the given refinement mapping.
* `abs!Extend`: `n2` is not the server with the longest log.

```tla
[...]

State 44: <MCSignCommittableMessages(n2) line 70, col 5 to line 71, col 37 of module MCccfraft>
/\ commitIndex = (n1 :> 6 @@ n2 :> 4)
/\ retirementCompleted = (n1 :> {} @@ n2 :> {n1})

/\ leadershipState = (n1 :> L_Follower @@ n2 :> L_Leader)
/\ membershipState = (n1 :> R_RetiredCommitted @@ n2 :> R_Active)
/\ currentTerm = (n1 :> 4 @@ n2 :> 5)
/\ log = (n1 :> <<[contentType |-> T_Reconfiguration, term |-> 2, configuration |-> {n1}], [contentType |-> T_Signature, term |-> 2], [contentType |-> T_Reconfiguration, term |-> 2, configuration |-> {n2}], [contentType |-> T_Signature, term |-> 2], [contentType |-> T_Retired, term |-> 4, retired |-> {n1}], [contentType |-> T_Signature, term |-> 4]>> @@ n2 :> <<[contentType |-> T_Reconfiguration, term |-> 2, configuration |-> {n1}], [contentType |-> T_Signature, term |-> 2], [contentType |-> T_Reconfiguration, term |-> 2, configuration |-> {n2}], [contentType |-> T_Signature, term |-> 2], [contentType |-> T_Retired, term |-> 4, retired |-> {n1}], [contentType |-> T_Signature, term |-> 4], [contentType |-> T_Signature, term |-> 5]>>)

State 45: <AdvanceCommitIndex(n2) line 845, col 5 to line 900, col 100 of module ccfraft>
/\ commitIndex = (n1 :> 6 @@ n2 :> 7)  \* <- CHANGED VALUE
/\ retirementCompleted = (n1 :> {} @@ n2 :> {}))  \* <- CHANGED VALUE

/\ membershipState = (n1 :> R_RetiredCommitted @@ n2 :> R_Active)
/\ leadershipState = (n1 :> L_Follower @@ n2 :> L_Leader)
/\ currentTerm = (n1 :> 4 @@ n2 :> 5)
/\ log = (n1 :> <<[contentType |-> T_Reconfiguration, term |-> 2, configuration |-> {n1}], [contentType |-> T_Signature, term |-> 2], [contentType |-> T_Reconfiguration, term |-> 2, configuration |-> {n2}], [contentType |-> T_Signature, term |-> 2], [contentType |-> T_Retired, term |-> 4, retired |-> {n1}], [contentType |-> T_Signature, term |-> 4]>> @@ n2 :> <<[contentType |-> T_Reconfiguration, term |-> 2, configuration |-> {n1}], [contentType |-> T_Signature, term |-> 2], [contentType |-> T_Reconfiguration, term |-> 2, configuration |-> {n2}], [contentType |-> T_Signature, term |-> 2], [contentType |-> T_Retired, term |-> 4, retired |-> {n1}], [contentType |-> T_Signature, term |-> 4], [contentType |-> T_Signature, term |-> 5]>>)
```

=> The underlying issue seems to be that the refinement does not take a server's retirement into account (`n1` is retired in all failed workflow runs).

**Comment by lemmy** [comment]
>> `MCccfraftWithReconfig` fails with an expected:
>> 
>> ```
>> Error: Evaluating action property line 51, col 20 to line 51, col 33 of module abs failed.
>> Attempted to construct a set with too many elements (>1000000).
>> ```
>
> @lemmy I am not sure I understand why the first one is expected, at first I thought the cLogs were getting big, but surely they're no bigger than the full logs we keep in ccfraft?


All newer workflow runs no longer fail with `Attempted to construct a set with too many elements (>1000000)`.  Instead, the newer workflow runs fail with the same counterexamples as in https://github.com/microsoft/CCF/pull/6493#issuecomment-2369650869.

**Comment by lemmy** [comment]
Attached are the log files for future reference, when we surpass the GitHub Action retention policy.: [logs_28684253808.zip](https://github.com/user-attachments/files/17105407/logs_28684253808.zip)

**Comment by lemmy** [comment]
One way to look at this discrepancy is to consider ccfraft more optimized than the high-level abs. The refinement would be valid if the server would advance its `commitindex` in two consecutive steps.

**Comment by achamayou** [comment]
> abs!Copy: n2 doesn't append a suffix from n1's log. Instead, it appends a suffix that seems unrelated, emerging unexpectedly based on the given refinement mapping.

Ah, that's what I was missing, it's a suffix from n1's log, but with an extra signature emitted by n2 at the end. This is expected, and potentially a feature of every post-election commit, whenever the newly elected leader's commit is lower than the previous leader's commit watermark.

This is not related to retirement, it can happen any time, but it is guaranteed to happen every time _the primary_ retires, because the primary will:

1. commit its retirement `(:44, ci := 7)`
2. nudge the backup to run `(:45)`
3. the backup becomes leader, with a commit index that's older `(:46, ci == 5)` (the backup had just acked, but never was told by the leader commit had advanced)
4. new leader emits a signature to advance commit in the new term `(:47, ci := 8)`, commit moves on, but neither Copy() nor Extend()

It can happen without retirement though, with a Timeout after commit index has progressed on the primary, but before the winner of the next election is aware of it. There will similarly be a new signature appended, and commit if it moves forward, will move directly to that signature.

Two thoughts:

1. It feels like this is a granularity problem, and can be fixed by adding `Copy() \cdot Extend()` to the state transitions
2. It also feels like there may be an optimisation, where the primary staples the latest commit index to the `ProposeRequestVote` message, prompting the backup to update its commit index and to run. That ought to work every time, because the primary selects a backup that will always have that index in their log. The benefit would be quite small (1RTT latency improvement on commit for a small number of transactions around hand-over).

**Comment by achamayou** [comment]
I tried this:

```
$ git diff
tla/consensus/abs.tla --- Text
57 57     \E i \in Servers : 
58 58         \/ Copy(i) 
59 59         \/ ExtendToMax(i)
.. 60         \/ Copy(i) \cdot ExtendToMax(i)
60 61 
61 62 AbsSpec == Init /\ [][Next]_cLogs
62 63 
```

But when running the basic consensus MC:

```
Reason:
In evaluation, the identifier commitIndex is either undefined or not an operator.
line 141, col 43 to line 141, col 53 of module MCccfraft
7805 states generated, 3433 distinct states found, 847 states left on queue.
The depth of the complete state graph search is 15.
```

Which sounds like using `commitIndex` in `MappingToAbs` is somehow illegal, but I do not understand why:

1. that only happens 15 states in
2. that does not happen when not adding the composite action

**Comment by lemmy** [comment]
> It can happen without retirement though, with a Timeout after commit index has progressed on the primary, but before the winner of the next election is aware of it. There will similarly be a new signature appended, and commit if it moves forward, will move directly to that signature.

Since we didn't observe a violation of refinement with `MCccfraft.tla/MCccfraft.cfg`, this indicates that it is likely over-constraining the state space.

> * that only happens 15 states in

All previous actions were either `Copy` or `Extend` actions.

> * that does not happen when not adding the composite action

This is a limitation of the *incomplete* `\cdot` implementation.

**Comment by lemmy** [comment]
https://github.com/microsoft/CCF/pull/6493/commits/41f014087cc0c56748ed9214dd51cfde5783850d has the following equivalent definition.  IMO, `CopyMaxAndExtend` makes it more obvious that it copies the *longest* cLog.

```tla
CopyMaxAndExtend(i, k) ==
    /\ \E j \in Servers :
        /\ \A r \in Servers: Len(cLogs[r]) \leq Len(cLogs[j])
        /\ \E l \in 0..(k - Len(cLogs[j])) : 
            \E s \in [1..l -> Terms] :
                cLogs' = [cLogs EXCEPT ![i] = cLogs[j] \o s]
```

**Comment by achamayou** [comment]
> > It can happen without retirement though, with a Timeout after commit index has progressed on the primary, but before the winner of the next election is aware of it. There will similarly be a new signature appended, and commit if it moves forward, will move directly to that signature.
> 
> Since we didn't observe a violation of refinement with `MCccfraft.tla/MCccfraft.cfg`, this indicates that it is likely over-constraining the state space.

I believe it does, we seem to set [MaxTermLimit = 2](https://github.com/microsoft/CCF/blob/main/tla/consensus/MCccfraft.cfg#L7), which is applied [strictly on timeouts](https://github.com/microsoft/CCF/blob/main/tla/consensus/MCccfraft.tla#L46). We initialise [currentTerm to StartTerm](https://github.com/microsoft/CCF/blob/main/tla/consensus/ccfraft.tla#L586), and [StartTerm = 2](https://github.com/microsoft/CCF/blob/main/tla/consensus/ccfraft.tla#L106). So I think we may not have *any* view changes in MCccfraft.cfg as it is.
 
> > * that only happens 15 states in
> 
> All previous actions were either `Copy` or `Extend` actions.
> 
> > * that does not happen when not adding the composite action
> 
> This is a limitation of the _incomplete_ `\cdot` implementation.

Ah, sorry, I did not remember that. It looks like [the composite action](https://github.com/microsoft/CCF/commit/41f014087cc0c56748ed9214dd51cfde5783850d) does get past the issue, but the the model checking takes considerably longer than previously, and is still going.

**Pull request closed without merging**
