### PR TITLE
Better error handling in ledger

### PR DESCRIPTION
**Pull request by achamayou**
Fix for #30

### CODE REVIEW

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Checking more return values") a bit more.
Would you like to detect every error situation as early as possible?

**Comment by achamayou** [comment]
@elfring what do you have in mind?

**Comment by elfring** [comment]
I suggest to take return values also from calls of the function “fseeko” better into account.
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for code analysis") also for this software?

**Comment by achamayou** [comment]
@elfring although it is possible to check return values for fseeko(), in this particular context, it isn't especially useful: they are immediately followed by fread(), after which point the data is sent to the enclave.

If the fd has been unexpectedly closed, the read will fail, immediately after. If the read happens, but at the wrong offset (which as far as I can tell isn't possible with typical ftello implementations anyway), the data will fail integrity and version checks in the enclave.

So there is no impact to not checking this return value. Note that all host code (ie. run outside the enclave) is untrusted, and assumed to be under control of a potential attacker. Only code inside the enclave is trusted.

As far as static analysis goes, we use clang with elevated warning levels as errors. Some of the code (crypto, merkle tree) is written in F*, on which some properties are formally verified before C code is generated. If you would like to open a PR setting up a new static analysis tool, we will be very happy to look at it and help.

**Comment by elfring** [comment]
>So there is no impact to not checking this return value.

I find such a view [insecure](https://wiki.sei.cmu.edu/confluence/display/c/ERR33-C.+Detect+and+handle+standard+library+errors "Detect and handle standard library errors.").

**Pull request merged**
