### PR TITLE
Allow RPC body to be given on command line

### PR DESCRIPTION
**Pull request by eddyashton**
Update `--req` options to the client binary with curl-style syntax, allowing load-from-file or specify-on-command-line.

So you can write:
```
$ ./client --pretty-print userrpc --req @listMethods.json
```
or
```
$ ./client --pretty-print userrpc --req '{"id": 1, "jsonrpc": "2.0", "method": "listMethods"}'
```

### CODE REVIEW

**Comment by jumaffre** [comment]
Is the `@` a little too [curl-specific](https://unix.stackexchange.com/a/144483)? I'd lean towards using two different CLI parameters (e.g. `--req` and `--req-file`) instead but happy to be convinced otherwise.

**Comment by eddyashton** [comment]
Having 2 options is trickier than I expected. We can do this:

```
std::pair<CLI::Option*, CLI::Option*> add_request_args(
  CLI::App* app, std::string& file, std::string& data)
{
  auto data_arg =
    app->add_option("--req", data, "RPC request data", !data.empty());

  auto file_arg = app->add_option(
    "--req-file",
    [&data](CLI::results_t res) {
      data = files::slurp_string(res[0]);
      return true;
    },
    "RPC request file",
    !file.empty());

  data_arg->excludes(file_arg);
  file_arg->excludes(data_arg);

  return {data_arg, file_arg};
}
```

But we can't neatly tell CLI11 to run this lambda on the default filename, or tell it that when we have no default for either value then at least one is required. I'll take another look at this tomorrow.

**Comment by olgavrou** [comment]
I know it's not the best thing to use try-catch to implement any sort of logic, but in this case I'd  either go with the @ or omit it and just try to slurp the input as a file, and if it fails then just continue assuming it is a string.

**Comment by achamayou** [comment]
@ is used outside curl as well, in the azure cli, in ansible etc, so it’s not unreasonable to go with it.

**Comment by eddyashton** [comment]
Let's call that multiple votes for @, merging as-is.

**Pull request merged**
