### PR TITLE
Automatically create Issue to track merging of lts-candidate labelled PRs

### PR DESCRIPTION
**Pull request by eddyashton**

### CODE REVIEW

**Comment by eddyashton** [comment]
Temporarily adding the label to this PR, to see how it works on this repo (previously tested on my fork).

**Comment by eddyashton** [comment]
Hmm. Adding the `lts-compatibility` label triggered this Action:
https://github.com/microsoft/CCF/runs/3136153247?check_suite_focus=true

which failed with a pretty opaque error. I saw this once when testing on my fork, because it didn't have Issues enabled, but this fork definitely does...

I'll try again?

**Comment by eddyashton** [comment]
Oh right, of course. A PR _from_ a fork, like all of our PRs are, doesn't get the secret to modify the repo (for good reason). But this means it also can't post an issue...

**Review by achamayou — APPROVED** [review]

**Comment by eddyashton** [comment]
Converting this to Draft for now, as its currently Green and Approved, but not actually working as intended. Still need to debug a permissions issue.

**Comment by eddyashton** [comment]
Closing this PR, as I can't set the desired permissions correctly. It should be possible to allow the GithubActions bot create Issues on our repo, even if this implicitly extended to Issues created from Actions triggered by untrusted forks, but this is still denied when actually running.

**Pull request closed without merging**
