### PR TITLE
Moving the TLA+ spec for consensus

### PR DESCRIPTION
**Pull request by heidihoward**
Moving the original TLA+ spec into its own sub directory under `/tla`

The docs also need to updating but I'll leave that for a separate PR

### CODE REVIEW

**Comment by achamayou** [comment]
> The docs also need to updating but I'll leave that for a separate PR

It would be preferable for that to be in the same PR if possible, otherwise we'll be publishing documentation with broken links in the interval.

It won't break the CI, because we've turned off the automated link checker after it proved noisy (out of the various websites we link to, there often seemed to be one or two that was down).

**Comment by heidihoward** [comment]
@achamayou I might be mistaken but I don't believe that there are any links to the relocated files in the docs. The only thing that would need updating due to this change is the examples here https://microsoft.github.io/CCF/main/architecture/raft_tla.html#running-the-model-checker but they are already out-of-date (e.g. the file `MCccfraftWithReconfig.tla` does not exist and `-workers auto` was recently removed from `tlc.sh`.

That being said I am happy to combine into one PR if that's preferred

**Comment by achamayou** [comment]
@heidihoward you're right, we used to have `literalincludes` pointing there, but we have since removed them it seems, so I have no objection.

**Review by achamayou — APPROVED** [review]

**Comment by lemmy** [comment]
Minor, but the wording in https://github.com/microsoft/CCF/blob/main/tla/README.md is outdate.

**Pull request merged**
