### PR TITLE
Update snmalloc from 0.5.0 to 0.5.2

### PR DESCRIPTION
**Pull request by achamayou**

### CODE REVIEW

**Review by eddyashton — APPROVED** [review]

**Comment by achamayou** [comment]
Interestingly, this upgrade is causing the following tests to fail reproducibly:

```
The following tests FAILED:
	 46 - full_test_suite (Failed)
	 69 - forum_app (Failed)
```

**Comment by achamayou** [comment]
There is a major performance regression in virtual mode, which is causing transaction times to double in the forum_app for example, and to timeout in others.

Run with snmalloc 0.5.0:

```
69: (Use `node --trace-warnings ...` to show where the warning was created)
69:         ✓ creates numeric polls (2817ms)
69:         ✓ creates string polls (2877ms)
69:         ✓ rejects creating polls with an existing topic (5591ms)
69:         ✓ rejects creating polls without authorization (2500ms)
69:       POST /
69:         ✓ creates multiple polls (2673ms)
69:         ✓ rejects creating polls with an existing topic (5406ms)
69:         ✓ rejects creating polls without authorization (2457ms)
69:       PUT /{topic}
69:         ✓ stores opinions to a topic (5572ms)
69:         ✓ rejects opinions with mismatching data type (5555ms)
69:         ✓ rejects opinions for unknown topics (2771ms)
69:         ✓ rejects opinions without authorization (5167ms)
69:       PUT /
69:         ✓ stores opinions to multiple topics (5465ms)
69:         ✓ rejects opinions with mismatching data type (5518ms)
69:         ✓ rejects opinions for unknown topics (2694ms)
69:         ✓ rejects opinions without authorization (5183ms)
69:       GET /{topic}
69:         ✓ returns aggregated numeric poll opinions (33325ms)
69:         ✓ returns aggregated string poll opinions (33694ms)
69:         ✓ rejects returning aggregated opinions below the required opinion count threshold (30365ms)
69:         ✓ rejects returning aggregated opinions for unknown topics (2766ms)
69:     /csv
69:       GET|POST /
69:         ✓ stores and returns opinions of authenticated user as CSV (4650ms)
```

0.5.2

```
74: (Use `node --trace-warnings ...` to show where the warning was created)
74:         ✓ creates numeric polls (6815ms)
74:         ✓ creates string polls (6788ms)
74:         ✓ rejects creating polls with an existing topic (13528ms)
74:         ✓ rejects creating polls without authorization (6455ms)
74:       POST /
74:         ✓ creates multiple polls (6653ms)
74:         ✓ rejects creating polls with an existing topic (13440ms)
74:         ✓ rejects creating polls without authorization (6425ms)
74:       PUT /{topic}
74:         ✓ stores opinions to a topic (13401ms)
74:         ✓ rejects opinions with mismatching data type (13508ms)
74:         ✓ rejects opinions for unknown topics (6666ms)
74:         ✓ rejects opinions without authorization (13211ms)
74:       PUT /
74:         ✓ stores opinions to multiple topics (13355ms)
74:         ✓ rejects opinions with mismatching data type (13420ms)
74:         ✓ rejects opinions for unknown topics (6683ms)
74:         ✓ rejects opinions without authorization (13080ms)
74:       GET /{topic}
74:         1) returns aggregated numeric poll opinions
74:         2) returns aggregated string poll opinions
74:         3) rejects returning aggregated opinions below the required opinion count threshold
74:         ✓ rejects returning aggregated opinions for unknown topics (21441ms)
74:     /csv
74:       GET|POST /
74:         4) stores and returns opinions of authenticated user as CSV
74: [15:24:38.849] Stopping all CCF nodes...
74: 
74: [15:24:43.685] All CCF nodes stopped.
```

**Comment by achamayou** [comment]
Ok so:

1. This goes away if LVI_MITIGATIONS are turned off
2. This is with everything (including snmalloc) built as Debug

**Comment by achamayou** [comment]
Bisected down to https://github.com/microsoft/snmalloc/commit/d3ecd66f732e7923b6ff939ad95be6601b70c367

**Comment by achamayou** [comment]
@mjp41 kindly made a tweak to the pow2 check code used by the assertion called in align_up/down (https://github.com/microsoft/snmalloc/pull/274), which does resolve the performance hit. Closing this for now, will re-open a 0.5.0 to 0.5.3 PR once available.

**Pull request closed without merging**
