### PR TITLE
Depend on static checks

### PR DESCRIPTION
**Pull request by jumaffre**
Make all build and test jobs depend on static check job. 

This might not be the best way to do this so let me know if there is.

### CODE REVIEW

**Comment by achamayou** [comment]
@jumaffre I've avoided doing that on purpose, otherwise none of the build jobs start until checks are done, and that adds another 30 seconds to the build. I suppose it's a glass half-full/empty situation, if you believe they will pass on average (and I do), it's best not to have the dependency and to run them concurrently.

If you believe they often fail and you want to save the rest of the build from running, then this is good. Arguably, a better thing would be to abort the other jobs, rather than have them as dependencies, but I don't know how to do that.

**Comment by cimetrics** [comment]
images

**Comment by jumaffre** [comment]
> @jumaffre I've avoided doing that on purpose, otherwise none of the build jobs start until checks are done, and that adds another 30 seconds to the build. I suppose it's a glass half-full/empty situation, if you believe they will pass on average (and I do), it's best not to have the dependency and to run them concurrently.
> 
> If you believe they often fail and you want to save the rest of the build from running, then this is good. Arguably, a better thing would be to abort the other jobs, rather than have them as dependencies, but I don't know how to do that.

@achamayou Good point. I agree that the static checks will/should be green more often than they're not. However, the cost of them not being green on `master` currently is quite high: 8 jobs * ~10 minutes (say, 80 minutes of executor time) will be run regardless (for a cost of only 30 seconds for each build). Without doing further maths, I think that even if this check fail 10% of the time, it's worth it ( out of 100 daily builds, cost is only 45 minutes of executor time per day). 

I don't really mind either way anyway ;)

**Comment by achamayou** [comment]
@jumaffre if we find a way to cancel on checks failure, but without gating the rest of the jobs, that would be ideal in terms of CI latency and executor utilisation.

**Comment by achamayou** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/process/phases?tabs=yaml&view=azure-devops#access-to-oauth-token Should allow us to run commands against the API. Then I think it would be updateBuild: https://docs.microsoft.com/en-gb/rest/api/azure/devops/build/builds/update%20build?view=azure-devops-rest-5.0

Not sure it’s worth the trouble. Being able to kill off the SAN and perf jobs if the functional tests have failures is somewhat appealing though. I think that’s considerably more frequent than the static checks failing.

**Comment by cimetrics** [comment]
images

**Pull request merged**
