### PR TITLE
Add details of last matching line in TV CI

### PR DESCRIPTION
**Pull request by achamayou**
Made possible by https://github.com/tlaplus/tlaplus/commit/f153944df690111878f521fc530ebc511a7e9892, sample output:

```
traces/append.ndjson
traces/election.ndjson
traces/reconnect.ndjson
traces/reconfiguration.ndjson
traces/multi_election.ndjson
traces/check_quorum.ndjson
traces/replicate.ndjson
traces/reelection.ndjson
traces/retire_one.ndjson
traces/startup.ndjson
traces/election_while_reconfiguration.ndjson
traces/startup_2nodes.ndjson
traces/soft_rollback.ndjson
traces/bad_network.ndjson
traces/swap_node_no_election.ndjson
"Last matched [181] send_append_entries (periodic_all,10)"
traces/suffix_collision.1.ndjson
traces/swap_node.ndjson
"Last matched [361] send_append_entries (periodic_all,10)"
traces/fancy_election.1.ndjson
traces/fancy_election.2.ndjson
```

We might want to add more context, but this at least lets us find quickly which scenario(s) failed, and where exactly.

### CODE REVIEW

**Review by eddyashton — APPROVED** [review]

**Comment by lemmy** [comment]
Keep in mind that focusing on the last state can be a red herring (see https://github.com/microsoft/CCF/pull/5989).

**Comment by lemmy** [comment]
> I know, but I claim this is better than showing nothing! :)

Yes.  In addition, we could consider [graph-easy](https://metacpan.org/pod/Graph::Easy), for which there is now TLC  relevant [infrastructure in TLC](https://github.com/tlaplus/tlaplus/commit/66708c72cb7df74ffe7fce18960f1552a007915e).

**Comment by lemmy** [comment]
Note https://github.com/microsoft/CCF/pull/5989#issuecomment-1949643102

**Comment by achamayou** [comment]
@lemmy tbh I am quite biased in favour of text where possible (being able to search, filter, display directly in terminal and CI are all really important), and not adding new programming languages unless strictly necessary. We generally manage for other tests, so I think we should be able to for the trace validation as well.

**Comment by lemmy** [comment]
> @lemmy tbh I am quite biased in favour of text where possible (being able to search, filter, display directly in terminal and CI are all really important), and not adding new programming languages unless strictly necessary. We generally manage for other tests, so I think we should be able to for the trace validation as well.

Perhaps, https://metacpan.org/pod/Graph::Easy makes it look as if graph-easy is a library, but it is a command-line tool that renders a graph in dot notation as ascii on stdout.

**Comment by achamayou** [comment]
@lemmy ah, yes, https://metacpan.org/dist/Graph-Easy/view/bin/graph-easy

**Pull request merged**
