### PR TITLE
OE 0.13 rc2

### PR DESCRIPTION
**Pull request by achamayou**
Address #2002

### CODE REVIEW

**Comment by achamayou** [comment]
Perf setup is expected to fail, since it isn't containerised and I haven't rolled out OE 0.13 there (yet). I will do once the rest of the CI looks good.

**Comment by achamayou** [comment]
Rev'ed up perf, since the rest looks ok.

**Comment by achamayou** [comment]
Perf looks in-line with 0.12.

**Comment by achamayou** [comment]
- [ ] .deb dependency constraint needs updating

**Review by eddyashton — APPROVED** [review]

**Review by wintersteiger — APPROVED** [review]
LGTM; thanks for the upgrade!

**Pull request merged**
