### PR TITLE
Another subset of small improvements of TLA+ specification listed in #4264

### PR DESCRIPTION
**Pull request by lemmy**

### CODE REVIEW

**Comment by lemmy** [comment]
The previous PR squashed all commits when merged into `main`.  The commits in this PR are independent of each other.  I'd suggest keeping the individual commits when merging.

**Comment by heidihoward** [comment]
> The previous PR squashed all commits when merged into `main`. The commits in this PR are independent of each other. I'd suggest keeping the individual commits when merging.

Thanks for highlighting this. Squashing commits is the default for this repo. We try to aim for small incremental PRs (but sometimes fail, as demonstrated by yours truly with https://github.com/microsoft/CCF/pull/3965).

@achamayou Is this something we easily modify on a per PR basis? or what workaround would you suggest? Markus's commit messages include useful context on the changes made.

**Comment by lemmy** [comment]
FYI: The motivation to extract/refactor what are essentially hardwired state constraints is strategically enabling simulation, liveness checking, bounded model-checking, and proofs.

**Comment by heidihoward** [comment]
> Thanks for highlighting this. Squashing commits is the default for this repo. We try to aim for small incremental PRs (but sometimes fail, as demonstrated by yours truly with #3965).
> 
> @achamayou Is this something we easily modify on a per PR basis? or what workaround would you suggest? Markus's commit messages include useful context on the changes made.

I discussed this with the team this morning and there is a preference for squashing for consistency with the other commits to main. The workflow for reviewing code history is to use `git praise` to go to the PR and then review the PR description/comments/commits for a more fine-grained explanation. 

This approach (along with a few other things) makes more sense for the production code than it does for the TLA+ spec. One solution is to put the TLA+ spec into a separate repo, but the idea behind having the spec live alongside the production code is to try to keep them both in sync (and maybe even enforce this one day with trace checking CI)

**Comment by lemmy** [comment]
I have a few more [commits pending](https://github.com/microsoft/CCF/compare/main...lemmy:CCF:mku-gh4264-4) that depend on the current commits in this PR.  Do you want me to push those into this or open more PRs?

**Comment by heidihoward** [comment]
Opening seperate PRs is preferable if that's ok with you

**Review by heidihoward — APPROVED** [review]

**Comment by heidihoward** [comment]
This PR is ready to be merged (the failure in daily is unrelated)

**Review by achamayou — APPROVED** [review]

**Pull request merged**
