### PR TITLE
Return the view that's relevant to the transaction, not the latest view!

### PR DESCRIPTION
**Pull request by achamayou**

### CODE REVIEW

**Comment by eddyashton** [comment]
In case anyone else is staring at this and pondering the implications: I initially thought this could be replaced with an error - if these views don't match then there's been a view change during execution and the transaction is about to be rolled back. But I believe its actually possible for a transaction to complete, be replicated, signed and globally committed, and then for a legitimate view change to occur, before the executing node reaches this point in constructing the response (the executing thread _could_ be stalled arbitrarily long, anywhere). This change is necessary in that situation, so the response headers correctly identify the executed transaction.

**Comment by achamayou** [comment]
@eddyashton yes, exactly, that'd have to happen pretty fast, but it could.

So this breaks some tests that incorrectly interpret the transaction term as being the current term when calling getPrimaryInfo (more often than not, around election time, it's not!). So I'm adding the current_term (as known by the node) to fix that.

Next up, the purge of global_commit from end to end tests and Python infra.

**Comment by achamayou** [comment]
Also to come, The Great Big Renaming of the HTTP headers, variable names and everything.

**Comment by achamayou** [comment]
@olgavrou interestingly, this fix seems to make #1127 happen reliably.

**Comment by olgavrou** [comment]
@achamayou view changes seem to be happening fine and there is no merkle root (or other) mismatch, so I am guessing it has to do with the commit/view assumptions

**Pull request merged**
