### PR TITLE
Fix EC JWK private key size calculation

### PR DESCRIPTION
**Pull request by jumaffre**
Fix https://github.com/microsoft/CCF/issues/4384

The size of the EC private key shouldn't be calculated from the big number as per https://www.openssl.org/docs/man1.0.2/man3/BN_num_bytes.html: 

> Some have tried using BN_num_bits() on individual numbers in RSA keys, DH keys and DSA keys, and found that they don't always come up with the number of bits they expected (something like 512, 1024, 2048, ...). This is because generating a number with some specific number of bits doesn't always set the highest bits, thereby making the number of significant bits a little lower. If you want to know the "key size" of such a key, either use functions like RSA_size(), DH_size() and DSA_size(), or use BN_num_bytes() and multiply with 8 (although there's no real guarantee that will match the "key size", just a lot more probability).

This would only occur rarely, when the first byte of the big number was `0x00`.

There's no easy way to test this against a well-known JWK implementation I don't think but I've confirmed the fix locally by running the specific `modules_test` successfully 100 times.

### CODE REVIEW

**Comment by eddyashton** [comment]
> This would only occur rarely, when the first byte of the big number was `0x00`.
> I've confirmed the fix locally by running the specific `modules_test` successfully 100 times.

I'd expect a null first byte approximately 1-in-256 runs, so 100 runs is only soft assurance. Assuming this is relatively fast, can you give it another few hundred iterations? Or perhaps throw a loud message somewhere once we have generated a key with a null first byte (when `BN_num_bytes` doesn't equal the new size?), and confirm that test run still passes?

**Review by wintersteiger — APPROVED** [review]
LGTM!

I would have gone through

```
EC_GROUP *g = EC_KEY_get0_group(ec);
int bits = EC_GROUP_order_bits(g);
```

But, I think `EVP_PKEY_bits` is the right way to do it (it's also in 3.0, while some parts of `EC_GROUP*` are not).

**Comment by wintersteiger** [comment]
+1 to test!

**Comment by jumaffre** [comment]
> > This would only occur rarely, when the first byte of the big number was `0x00`.
> > I've confirmed the fix locally by running the specific `modules_test` successfully 100 times.
> 
> I'd expect a null first byte approximately 1-in-256 runs, so 100 runs is only soft assurance. Assuming this is relatively fast, can you give it another few hundred iterations? Or perhaps throw a loud message somewhere once we have generated a key with a null first byte (when `BN_num_bytes` doesn't equal the new size?), and confirm that test run still passes?
> 
> EDIT - Or even stronger - can you generate this key in a loop until we get one with a null initial byte, confirm that's the cause of the initial failure, confirm the new calc fixes it?

The `modules_test` generates 3 EC keys, hence the value of 100 as a loose threshold over the 256 mark. I've run this 500 times over lunch (so 1,500 keys) and the test passed successfully. The issue was identified and fixed exactly as you describe though (check the size of the private key, log an error if it's not a number we expect, fix the issue and make sure it succeeds when the size of the private key isn't as expected) but this scaffolding isn't something I intend to leave in the codebase.

**Review by eddyashton — APPROVED** [review]

**Pull request merged**
