### PR TITLE
Pending nodes must not be part of a configuration.

### PR DESCRIPTION
**Pull request by lemmy**
A pending node has passed attestation checks, but is waiting for member confirmation, and just isn't part of any configurations at all, nor has a communication channel with other nodes (Pending is *not* Learner in https://microsoft.github.io/CCF/main/architecture/consensus/1tx-reconfig.html).

### CODE REVIEW

**Comment by achamayou** [comment]
LGTM, but @heidihoward please confirm.

**Review by heidihoward — APPROVED** [review]
lgtm

**Comment by lemmy** [comment]
Apologies, `PendingNeverConfigurationInv` is bogus and allows for a pending node to become part of a configuration.  The stronger `PendingNeverConfigurationInv` 

```tla
PendingNeverConfigurationInv ==
    \* A pending node is never part of a configuration.
    \A s \in Servers : 
        \A i \in DOMAIN configurations[s] :
            \A c \in configurations[s][i] : 
                state[c] # Pending
```

is violated by the following trace:

```tla
Invariant PendingNeverConfigurationInv is violated.
The behavior up to this point is:
1: <Initial predicate>
/\ configurations = ( n1 :> (0 :> {n3}) @@
  n2 :> (0 :> {n3}) @@
  n3 :> (0 :> {n3}) @@
  n4 :> (0 :> {n3}) @@
  n5 :> (0 :> {n3}) )
/\ removedFromConfiguration = {}
/\ nextIndex = ( n1 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n2 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n3 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n4 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n5 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) )
/\ reconfigurationCount = 0
/\ currentTerm = (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1)
/\ votedFor = (n1 :> Nil @@ n2 :> Nil @@ n3 :> Nil @@ n4 :> Nil @@ n5 :> Nil)
/\ messagesSent = ( n1 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n2 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n3 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n4 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n5 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) )
/\ commitsNotified = ( n1 :> <<0, 0>> @@
  n2 :> <<0, 0>> @@
  n3 :> <<0, 0>> @@
  n4 :> <<0, 0>> @@
  n5 :> <<0, 0>> )
/\ matchIndex = ( n1 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n2 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n3 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n4 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n5 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) )
/\ commitIndex = (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0)
/\ state = ( n1 :> Pending @@
  n2 :> Pending @@
  n3 :> Follower @@
  n4 :> Pending @@
  n5 :> Pending )
/\ votesRequested = ( n1 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n2 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n3 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n4 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n5 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) )
/\ messages = {}
/\ log = (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>)
/\ clientRequests = 1
/\ votesGranted = (n1 :> {} @@ n2 :> {} @@ n3 :> {} @@ n4 :> {} @@ n5 :> {})
/\ committedLog = [index |-> 0, node |-> n1]
2: <Timeout line 398, col 5 to line 416, col 74 of module ccfraft>
/\ configurations = ( n1 :> (0 :> {n3}) @@
  n2 :> (0 :> {n3}) @@
  n3 :> (0 :> {n3}) @@
  n4 :> (0 :> {n3}) @@
  n5 :> (0 :> {n3}) )
/\ removedFromConfiguration = {}
/\ nextIndex = ( n1 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n2 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n3 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n4 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n5 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) )
/\ reconfigurationCount = 0
/\ currentTerm = (n1 :> 1 @@ n2 :> 1 @@ n3 :> 2 @@ n4 :> 1 @@ n5 :> 1)
/\ votedFor = (n1 :> Nil @@ n2 :> Nil @@ n3 :> n3 @@ n4 :> Nil @@ n5 :> Nil)
/\ messagesSent = ( n1 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n2 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n3 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n4 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n5 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) )
/\ commitsNotified = ( n1 :> <<0, 0>> @@
  n2 :> <<0, 0>> @@
  n3 :> <<0, 0>> @@
  n4 :> <<0, 0>> @@
  n5 :> <<0, 0>> )
/\ matchIndex = ( n1 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n2 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n3 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n4 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n5 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) )
/\ commitIndex = (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0)
/\ state = ( n1 :> Pending @@
  n2 :> Pending @@
  n3 :> Candidate @@
  n4 :> Pending @@
  n5 :> Pending )
/\ votesRequested = ( n1 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n2 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n3 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n4 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n5 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) )
/\ messages = {}
/\ log = (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>)
/\ clientRequests = 1
/\ votesGranted = (n1 :> {} @@ n2 :> {} @@ n3 :> {n3} @@ n4 :> {} @@ n5 :> {})
/\ committedLog = [index |-> 0, node |-> n1]
3: <BecomeLeader line 479, col 5 to line 498, col 82 of module ccfraft>
/\ configurations = ( n1 :> (0 :> {n3}) @@
  n2 :> (0 :> {n3}) @@
  n3 :> (0 :> {n3}) @@
  n4 :> (0 :> {n3}) @@
  n5 :> (0 :> {n3}) )
/\ removedFromConfiguration = {}
/\ nextIndex = ( n1 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n2 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n3 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n4 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n5 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) )
/\ reconfigurationCount = 0
/\ currentTerm = (n1 :> 1 @@ n2 :> 1 @@ n3 :> 2 @@ n4 :> 1 @@ n5 :> 1)
/\ votedFor = (n1 :> Nil @@ n2 :> Nil @@ n3 :> n3 @@ n4 :> Nil @@ n5 :> Nil)
/\ messagesSent = ( n1 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n2 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n3 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n4 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n5 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) )
/\ commitsNotified = ( n1 :> <<0, 0>> @@
  n2 :> <<0, 0>> @@
  n3 :> <<0, 0>> @@
  n4 :> <<0, 0>> @@
  n5 :> <<0, 0>> )
/\ matchIndex = ( n1 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n2 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n3 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n4 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n5 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) )
/\ commitIndex = (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0)
/\ state = ( n1 :> Pending @@
  n2 :> Pending @@
  n3 :> Leader @@
  n4 :> Pending @@
  n5 :> Pending )
/\ votesRequested = ( n1 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n2 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n3 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n4 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n5 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) )
/\ messages = {}
/\ log = (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>)
/\ clientRequests = 1
/\ votesGranted = (n1 :> {} @@ n2 :> {} @@ n3 :> {n3} @@ n4 :> {} @@ n5 :> {})
/\ committedLog = [index |-> 0, node |-> n1]
4: <Next line 956, col 27 to line 956, col 105 of module ccfraft>
/\ configurations = ( n1 :> (0 :> {n3}) @@
  n2 :> (0 :> {n3}) @@
  n3 :> (0 :> {n3} @@ 1 :> {n1}) @@
  n4 :> (0 :> {n3}) @@
  n5 :> (0 :> {n3}) )
/\ removedFromConfiguration = {n3}
/\ nextIndex = ( n1 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n2 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n3 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n4 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) @@
  n5 :> (n1 :> 1 @@ n2 :> 1 @@ n3 :> 1 @@ n4 :> 1 @@ n5 :> 1) )
/\ reconfigurationCount = 1
/\ currentTerm = (n1 :> 1 @@ n2 :> 1 @@ n3 :> 2 @@ n4 :> 1 @@ n5 :> 1)
/\ votedFor = (n1 :> Nil @@ n2 :> Nil @@ n3 :> n3 @@ n4 :> Nil @@ n5 :> Nil)
/\ messagesSent = ( n1 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n2 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n3 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n4 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) @@
  n5 :> (n1 :> <<>> @@ n2 :> <<>> @@ n3 :> <<>> @@ n4 :> <<>> @@ n5 :> <<>>) )
/\ commitsNotified = ( n1 :> <<0, 0>> @@
  n2 :> <<0, 0>> @@
  n3 :> <<0, 0>> @@
  n4 :> <<0, 0>> @@
  n5 :> <<0, 0>> )
/\ matchIndex = ( n1 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n2 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n3 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n4 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n5 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) )
/\ commitIndex = (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0)
/\ state = ( n1 :> Pending @@
  n2 :> Pending @@
  n3 :> Leader @@
  n4 :> Pending @@
  n5 :> Pending )
/\ votesRequested = ( n1 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n2 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n3 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n4 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) @@
  n5 :> (n1 :> 0 @@ n2 :> 0 @@ n3 :> 0 @@ n4 :> 0 @@ n5 :> 0) )
/\ messages = {}
/\ log = ( n1 :> <<>> @@
  n2 :> <<>> @@
  n3 :> <<[contentType |-> Reconfiguration, term |-> 2, value |-> {n1}]>> @@
  n4 :> <<>> @@
  n5 :> <<>> )
/\ clientRequests = 1
/\ votesGranted = (n1 :> {} @@ n2 :> {} @@ n3 :> {n3} @@ n4 :> {} @@ n5 :> {})
/\ committedLog = [index |-> 0, node |-> n1]
```

A node transitions from `pending` to `follower` in `AcceptAppendEntriesRequest` (`NoConflictAppendEntriesRequest`).  In other words, the leader has to first send the pending node an append message in `AppendEntries`.

Is this in line with the implementation?

**Comment by heidihoward** [comment]
> 
> A node transitions from `pending` to `follower` in `AcceptAppendEntriesRequest` (`NoConflictAppendEntriesRequest`). In other words, the leader has to first send the pending node an append message in `AppendEntries`.
> 
> Is this in line with the implementation?

Yes, I believe so. A newly added node does not transition to follower until its appends the transaction that added it

**Review by achamayou — APPROVED** [review]

**Pull request merged**
