### PR TITLE
Validate committable indices

### PR DESCRIPTION
**Pull request by lemmy**

### CODE REVIEW

**Comment by lemmy** [comment]
This subsequence of the trace of fancy_election.2 (projected for node 4) shows that `committable_indices` has to be modeled explicitly:

```json
{"h_ts":"697","thread_id":"100","level":"debug","tag":"raft_trace","file":"../src/consensus/aft/raft.h","number":"1627","msg":{"committable_indices":4,"from_node_id":"2","function":"recv_request_vote_response","packet":{"msg":"raft_request_vote_response","term":4,"vote_granted":true},"state":{"commit_idx":0,"current_view":4,"last_idx":4,"leadership_state":"Candidate","membership_state":"Active","new_view_idx":0,"node_id":"4","watermark_idx":2}}}
{"h_ts":"702","thread_id":"100","level":"debug","tag":"raft_trace","file":"../src/consensus/aft/raft.h","number":"1805","msg":{"committable_indices":0,"configurations":[{"idx":0,"nodes":{"0":{"address":":"},"1":{"address":":"},"2":{"address":":"},"3":{"address":":"},"4":{"address":":"}},"rid":0}],"function":"become_leader","state":{"commit_idx":0,"current_view":4,"last_idx":4,"leadership_state":"Leader","membership_state":"Active","new_view_idx":0,"node_id":"4","watermark_idx":2}}}
```

Upon becoming leader, node 4 resets its `committable_indices` but retains its four log entries `last_idx`.

**Review by achamayou — APPROVED** [review]

**Comment by achamayou** [comment]
> This subsequence of the trace of fancy_election.2 (projected for node 4) shows that `committable_indices` has to be modeled explicitly:
> 
> ```json
> {"h_ts":"697","thread_id":"100","level":"debug","tag":"raft_trace","file":"../src/consensus/aft/raft.h","number":"1627","msg":{"committable_indices":4,"from_node_id":"2","function":"recv_request_vote_response","packet":{"msg":"raft_request_vote_response","term":4,"vote_granted":true},"state":{"commit_idx":0,"current_view":4,"last_idx":4,"leadership_state":"Candidate","membership_state":"Active","new_view_idx":0,"node_id":"4","watermark_idx":2}}}
> {"h_ts":"702","thread_id":"100","level":"debug","tag":"raft_trace","file":"../src/consensus/aft/raft.h","number":"1805","msg":{"committable_indices":0,"configurations":[{"idx":0,"nodes":{"0":{"address":":"},"1":{"address":":"},"2":{"address":":"},"3":{"address":":"},"4":{"address":":"}},"rid":0}],"function":"become_leader","state":{"commit_idx":0,"current_view":4,"last_idx":4,"leadership_state":"Leader","membership_state":"Active","new_view_idx":0,"node_id":"4","watermark_idx":2}}}
> ```
> 
> Upon becoming leader, node 4 resets its `committable_indices` but retains its four log entries `last_idx`.

The rationale for this is that a newly elected leader cannot commit pre-election indices, and must instead issue its own committable entry post-election to move commit. So pre-election committable indices are not longer committable in effect, and are therefore cleared.

**Comment by lemmy** [comment]
Asserting `LastCommittableIndex(logline.msg.state.node_id) = logline.msg.committable_indices` in `Traceccfraft!IsRcvRequestVoteResponse` introduces a regression s.t. `fancy_election.2` (with `TraceMatched` relaxed from `{1,2}` to `{1,2,3}` fails to match at level 206 and ts "706" instead of failing at level 232 and ts "795".

**Comment by lemmy** [comment]
@achamayou, you gave your approval to this pull request *prior to* my modifications in `raft.h`. The only significant change is that `CCF_RAFT_TRACING` now logs the *list* of `committable_indices`. Does this change still meet with your approval?

**Comment by lemmy** [comment]
Could the build timeout be related to `CCF_RAFT_TRACING` logging *all* committable_indices?  If yes, can we run CTest without tracing?

**Comment by achamayou** [comment]
> Could the build timeout be related to `CCF_RAFT_TRACING` logging _all_ committable_indices? If yes, can we run CTest without tracing?

Yes, you tried this before in #5329 :)

In the interval, Eddy has made changes that make it possible to adjust the log level at runtime for platforms other than SGX, but that's through the config in CCF itself, it's not particularly exposed by the unit test binaries, let alone through ctest.

Aside from this, logging the whole committable indices on a per message basis remains problematic for all but short driver scenarios, since it potentially leads to quadratic log growth. I am not sure it will be practical for end to end tests, or even hypothetical production tracing.

Perhaps the best compromise here is to do a separate build of just the driver (as opposed to all the targets) with the tracing turned on, for the purpose of trace validation. This requires a bit of yaml fiddling (because we parametrise cmake at the top level), but I can do it tomorrow.

**Comment by lemmy** [comment]
> 
> Perhaps the best compromise here is to do a separate build of just the driver (as opposed to all the targets) with the tracing turned on, for the purpose of trace validation. This requires a bit of yaml fiddling (because we parametrise cmake at the top level), but I can do it tomorrow.

Thanks, that would be great.  I anticipate that once `committableIndices` is accurately modeled in the spec, we can relax trace validation to simply match `committableIndices`' maximum value.

**Comment by lemmy** [comment]
Depends on https://github.com/microsoft/CCF/pull/5656

**Review by achamayou — APPROVED** [review]

**Pull request merged**
