### PR TITLE
TLA changes do not require CI runs, yet.

### PR DESCRIPTION
**Pull request by achamayou**

### CODE REVIEW

**Comment by achamayou** [comment]
Should unblock things like #4439, #4438, #4437, #4436 etc.

**Review by MahatiC — APPROVED** [review]

**Comment by MahatiC** [comment]
This actually came up in today's stand-up!

**Review by eddyashton — APPROVED** [review]

**Review by heidihoward — APPROVED** [review]
Thanks! This will be very helpful when it comes to merging in TLA+ PRs quickly

**Comment by lemmy** [comment]
Motivated by https://github.com/microsoft/CCF/issues/4472, where would I start integrating TLA+ simulation with a time-budget into the [build/PR workflow](https://github.com/microsoft/CCF/tree/main/.github/workflows)?

**Comment by achamayou** [comment]
@lemmy adding a new workflow would be fantastic if you have time. If you don't, but you can drop a few pointers in a issue, we can pick it up. If it needs beefier kit than what's available by default, we can set up a hosted 1es pool.

**Pull request merged**
