### PR TITLE
Test large js app bundle

### PR DESCRIPTION
**Pull request by letmaik**
I'm trying to reproduce https://github.com/microsoft/CCF/issues/2297 but so far without luck. While doing that I wrote a test which leads to one of the following errors:

```
terminating with uncaught exception of type std::logic_error: Requested a write of 17896166 bytes, max allowed is 16777216
Stack trace (most recent call last) in thread 2721:
#19   Object "[0xffffffffffffffff]", at 0xffffffffffffffff, in 
#18   Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f3029b70a3e, in clone
#17   Object "/lib/x86_64-linux-gnu/libpthread.so.0", at 0x7f302a3fd6da, in 
#16   Object "./cchost.virtual", at 0x4227f6, in 
#15   Object "./cchost.virtual", at 0x4be637, in 
#14   Object "./libjs_generic.virtual.so", at 0x7f2f292b030f, in enclave_run
#13   Object "./libjs_generic.virtual.so", at 0x7f2f292bc137, in enclave::Enclave::run_main()
#12   Object "./libjs_generic.virtual.so", at 0x7f2f29423c7e, in threading::ThreadMessaging::run_one()
#11   Object "./libjs_generic.virtual.so", at 0x7f2f293e5171, in ccf::Snapshotter::snapshot_cb(std::__1::unique_ptr<threading::Tmsg<ccf::Snapshotter::SnapshotMsg>, std::__1::default_delete<threading::Tmsg<ccf::Snapshotter::SnapshotMsg> > >)
#10   Object "./libjs_generic.virtual.so", at 0x7f2f293e5587, in ccf::Snapshotter::snapshot_(std::__1::unique_ptr<kv::AbstractStore::AbstractSnapshot, std::__1::default_delete<kv::AbstractStore::AbstractSnapshot> >)
#9    Object "./libjs_generic.virtual.so", at 0x7f2f293e6837, in void ringbuffer::write_message_with_error_wrapper<715361165u, std::__1::shared_ptr<ringbuffer::AbstractWriter>&, unsigned long&, unsigned long&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&>(char const*, std::__1::shared_ptr<ringbuffer::AbstractWriter>&, unsigned long&, unsigned long&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&)
#8    Object "./libjs_generic.virtual.so", at 0x7f2f293e6a79, in bool ringbuffer::AbstractWriter::write_multiple<ringbuffer::MessageSerializers<715361165u>, unsigned long&, unsigned long&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&>(unsigned int, bool, unsigned long&, unsigned long&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&)
#7    Object "./libjs_generic.virtual.so", at 0x7f2f292be8e2, in oversized::Writer::prepare(unsigned int, unsigned long, bool, unsigned long*)
#6    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f302af30830, in __cxa_throw
#5    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f302af308a5, in 
#4    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f302af2db55, in 
#3    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f302af17f1e, in 
#2    Object "/usr/lib/x86_64-linux-gnu/libc++abi.so.1", at 0x7f302af2ea4f, in 
#1    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f3029a8f8b0, in abort
#0    Object "/lib/x86_64-linux-gnu/libc.so.6", at 0x7f3029a8df47, in gsignal
Aborted (Signal sent by tkill() 2720 1000)
```

I don't think the above should happen. The js app in this case has a size of ~2 MiB. The error only appears sometimes and I never saw it for the ~5 MiB test case.

Another error is the following, for the ~5 MiB test case:

```
12:09:57.780 | INFO     | __main__:test_app_bundle_large:156 - Deploying js app bundle: ~5 MiB
12:09:57.826 | DEBUG    | infra.consortium:make_proposal:139 - Writing proposal to .../CCF/build/workspace/modules_test_common/deploy_js_app_proposal.json
12:09:57.856 | DEBUG    | infra.consortium:make_proposal:143 - Writing vote to .../CCF/build/workspace/modules_test_common/deploy_js_app_vote_for.json
12:09:58.092 | INFO     | infra.member:propose:122 - [0|member2|member2] POST /gov/proposals @.../CCF/build/workspace/modules_test_common/deploy_js_app_proposal.json
12:09:58.092 | INFO     | infra.member:propose:122 - 200 @2.32 {"proposal_id":"abd8702abc88ce512a14bcd4947b219a38dbd955d4b0ba569cafb818539efc8f","proposer_id":"da460e609c6a8af15b14301d90d41f9 + 50 chars
12:09:58.399 | INFO     | infra.member:vote:136 - [0|member0|member0] POST /gov/proposals/abd8702abc88ce512a14bcd4947b219a38dbd955d4b0ba569cafb818539efc8f/votes @.../CCF/build/workspace/modules_test_common/deploy_js_app_vote_for.json
12:09:58.399 | INFO     | infra.member:vote:136 - 200 @2.33 {"proposal_id":"abd8702abc88ce512a14bcd4947b219a38dbd955d4b0ba569cafb818539efc8f","proposer_id":"da460e609c6a8af15b14301d90d41f9 + 50 chars
12:09:58.803 | INFO     | infra.remote:stop:489 - [127.201.70.234] closing
12:09:58.825 | ERROR    | infra.remote:log_errors:70 - .../CCF/build/workspace/modules_test_0/out: 2021-03-11T12:09:58.726899Z -0.241 0   [fail ] ../src/kv/tx.h:389                   | Error during serialisation
12:09:58.825 | ERROR    | infra.remote:log_errors:70 - .../CCF/build/workspace/modules_test_0/out: 2021-03-11T12:09:58.726908Z -0.241 0   [fatal] ../src/node/rpc/frontend.h:405       | Failed to serialise
12:09:58.825 | INFO     | infra.remote:log_errors:73 - 2 errors found, printing end of output for context:
12:09:58.825 | INFO     | infra.remote:log_errors:77 - 2021-03-11T12:09:58.506401Z -0.021 0   [trace] ../src/http/http_endpoint.h:167      | Processing msg(POST, /gov/proposals/abd8702abc88ce512a14bcd4947b219a38dbd955d4b0ba569cafb818539efc8f/votes, , [5248683 bytes])
12:09:58.825 | INFO     | infra.remote:log_errors:77 - 2021-03-11T12:09:58.683059Z -0.197 0   [debug] ../src/kv/store.h:932                | Store::commit 34
12:09:58.825 | INFO     | infra.remote:log_errors:77 - 2021-03-11T12:09:58.726873Z -0.241 0   [debug] ../src/node/history.h:86             | History [append] <sha256 12eb5f98bf0bc468cc429fa6ddebede2df41444c9f2c818c8901bcb80ff2e45b>
12:09:58.825 | INFO     | infra.remote:log_errors:77 - 2021-03-11T12:09:58.726890Z -0.241 0   [debug] ../src/kv/store.h:988                | Batching 34 (26237042)
12:09:58.825 | INFO     | infra.remote:log_errors:77 - 2021-03-11T12:09:58.726894Z -0.241 0   [debug] ../src/consensus/aft/raft.h:478      | Replicating 1 entries
12:09:58.825 | INFO     | infra.remote:log_errors:77 - 2021-03-11T12:09:58.726897Z -0.241 0   [debug] ../src/consensus/aft/raft.h:492      | Replicated on leader 8b6d972bc2: 34 (0 hooks)
12:09:58.825 | INFO     | infra.remote:log_errors:77 - 2021-03-11T12:09:58.726899Z -0.241 0   [fail ] ../src/kv/tx.h:389                   | Error during serialisation
12:09:58.826 | INFO     | infra.remote:log_errors:77 - 2021-03-11T12:09:58.726902Z -0.241 0   [debug] ../src/kv/tx.h:390                   | Error during serialisation: Requested a write of 26237044 bytes, max allowed is 16777216
```

### CODE REVIEW

**Comment by eddyashton** [comment]
So this potential issue was known and tracked in #1858, but I'm surprised we're seeing it with relatively small apps. @letmaik, can you log the size of the `serialised_snapshot` so we can see if it was surprisingly large _before_ this app, or its just this 2MB app which has produced a snapshot many times larger. As a related test, if you submit multiple 1MB or 0.5MB apps in series, do you hit the same issue? Or only with a single large app?

**Comment by letmaik** [comment]
I don't get any snapshots with any of the other tests. I can confirm that deploying many small js bundles in sequence also reproduces the error consistently, in this case 10 times each 0.5 MiB. `serialised_snapshot: 19593830`

**Comment by achamayou** [comment]
@letmaik could you create a corresponding ticket please?

**Comment by letmaik** [comment]
The case of repeatedly deploying small JS apps leading to a crash is essentially https://github.com/microsoft/CCF/issues/1401 where many proposals are accumulated in the kv, which leads to a large kv and hence large snapshot. I believe you're about to fix this, so I'll not create an issue for it, but let me know if I should anyway.
The other case of deploying a 5 MiB JS app just once happens because the resulting transaction has the app replicated in multiple tables (proposals, modules, and some history table) and that leads to a message larger than the maximum allowed size. This will be fixed with https://github.com/microsoft/CCF/issues/1858 but is not critical for 1.0 I think.

**Pull request closed without merging**
