### PR TITLE
Fix Signatures Table Name in Python Ledger module

### PR DESCRIPTION
**Pull request by syhamza**
Fixing Signatures table name as defined in CCF here: https://github.com/microsoft/CCF/blob/master/src/node/entities.h#L96

### CODE REVIEW

**Review by achamayou — APPROVED** [review]
Thank you! We unfortunately do not have an end to end test that validates signatures from the ledger using the Python API, which would have caught this.

**Review by jumaffre — APPROVED** [review]

**Review by eddyashton — APPROVED** [review]

**Comment by jumaffre** [comment]
Merging this as the failure on the Daily CI is unrelated to this change.

**Pull request merged**
