### PR TITLE
Python infra: fix MemberStatus enum parsing

### PR DESCRIPTION
**Pull request by letmaik**
Fixes daily build which [is broken](https://dev.azure.com/MSRC-CCF/CCF/_build/results?buildId=20791&view=logs&j=5435e0ac-25e5-5426-50be-61b0d0ea8d34&t=fe98d859-2537-5570-75af-de67d4290f3a)

### CODE REVIEW

**Review by jumaffre — APPROVED** [review]

**Comment by jumaffre** [comment]
You may want to touch the https://github.com/microsoft/CCF/blob/main/.daily_canary file to make sure the Daily is indeed fixed before merging this.

**Review by achamayou — APPROVED** [review]

**Comment by achamayou** [comment]
Modifying the Daily Build Status job to grep the PR title/branch name for "[Fix daily]"/fix_daily and pass automatically when that's the case to avoid having to use the red button to fix the daily build: Crazy or not?

**Comment by eddyashton** [comment]
> Modifying the Daily Build Status job to grep the PR title/branch name for "[Fix daily]"/fix_daily and pass automatically when that's the case to avoid having to use the red button to fix the daily build: Crazy or not?

Could we at least combine this with a check that the daily canary is modified? So Daily Status passes if (Daily CI is green) OR ((this PR says its fixing the Daily) AND (this PR will be gated by its own Daily run))?

**Review by eddyashton — APPROVED** [review]

**Comment by achamayou** [comment]
@eddyashton I like that!

**Pull request merged**
