### PR TITLE
Kv conflict resolution

### LINKED ISSUE #865: Tx write sets are not cleared on conflict
Further to #834, we have an issue that conflicting write sets are retained. Since frontend.h reruns the handler function using the same `Tx` object, we will actually produce a union write set. It may conflict again due to old writes, or worse it may produce what should be an impossible write set.

We should clear the write set during commit, if a conflict is discovered, and add a test for this in `kv_test`. Separately it may be worth adding a similar thread in `frontend_test`, which uses locks to interleave handler execution to force conflicts, to ensure we see the expected results externally.

### PR DESCRIPTION
**Pull request by eddyashton**
Resolves #865.

Adds a kv test of conflicting transactions, confirms that the new behaviour does what we expect. We may want to add more tests of this, to confirm that conflicts happen exactly when we expect. In particular I think a `frontend_test` that confirms the _real_ behaviour of conflicting-then-retried transactions would be worthwhile.

### CODE REVIEW

**Comment by achamayou** [comment]
Good catch!

**Comment by eddyashton** [comment]
This doesn't work in the PBFT case, as we have a pre-populated Tx.

**Comment by eddyashton** [comment]
Summary of comments lost to the sands of downtime: PBFT concern is not an issue as PBFT transactions are ordered on primary and shouldn't conflict, #868 should make this safer by _ensuring_ we don't get conflicts in PBFT case, I'd like to explore moving back to the old flow of constructing the Tx only where its used and discarding on failure but this will wait for the kv-API cleanup/minimisation pass.

**Comment by cimetrics** [comment]
kv_conflict_resolution@[5089 aka 20200219.31](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=5089&view=results) vs master ewma over 30 builds from [4699](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=4699&view=results) to [5085](https://msrc-ccf.visualstudio.com/CCF/_build/results?buildId=5085&view=results)
images

**Pull request merged**
